version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.build.json:/app/tsconfig.build.json
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: Admin1234;
      DB_DATABASE: charity
      JWT_SECRET: CO7*cpM$U999GfMT
    depends_on:
      - postgres  
    restart: always

  postgres:
    image: postgres:13.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin1234;
      POSTGRES_DB: charity